### ISSUE TITLE
Setting cookie attributes and root domain

### ISSUE THREAD

**Issue by awoehrl** [mint-metrics/mojito#4]
I've looked around in the documentation, but I couldn't find anything regarding setting Secure or SameSite attributes for the mojito cookie. Is this possible already?
Also the root domain seems to be fixed as well? I was looking for an option to set it to .foo.bar instead of www.foo.bar.

Cheers!

**Comment by kingo55** [comment]
Hi @awoehrl - apologies I didn't see this until now.

We have an issue for this, and it's something we'll support shortly - it's not something we've had a use for previously, but I realise this would be quite important for consistent assignment across subdomains:

https://github.com/mint-metrics/mojito-js-delivery/issues/94

**Comment by awoehrl** [comment]
Hi @kingo55,

thank you for your reply! I didn't realize I was looking in the wrong repository, hence I missed the existing issue. Glad to hear that this could be supported soon.

Cheers
